### ISSUE TITLE
OutOfMemoryError/ NegativeArraySizeException on large arrays

### ISSUE THREAD

**Issue by mprevel** [meyfa/java-sha256#2]
Hello,

`Sha256:95 int newMessageLength = message.length + 1 + 8;` can lead to a negative value that is used at `Sha256:100 final byte[] paddedMessage = new byte[newMessageLength];` when message. length is greater than `Integer.MAX_VALUE - 9` and resulting in a `NegativeArraySizeException`.

It may also lead to an `OutOfMemoryError` when building the array with an integer near `Integer.MAX_VALUE` since array max size is platform specific and can be a few bytes under `Integer_MAX_VALUE`.

**Comment by meyfa** [comment]
Confirmed. Probably needs a major overhaul of the padding logic for this to be fixed, but is doable because of the block-wise nature of SHA256.

**Comment by meyfa** [comment]
I hope to have fixed this issue in the latest commits. Please feel free to comment or open another issue if you notice anything else. Thanks!
